package base;

import implementasi.Tree;
import implementasi.TreeExit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Date;

public class dashboard extends javax.swing.JFrame {

    private FormLogin formLogin;
    private Tree tree;
    private TreeExit treeExit;
    public dashboard(Tree tree, TreeExit treeExit) {
        this.tree = tree;
        this.treeExit = treeExit;
        initComponents();
    }

    private void getDataDatabase() throws SQLException {

        try {
            Connection conn = Koneksi.getkoneksi();
            String query = "SELECT * FROM entry";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                int ticketNumber = rs.getInt("ticketNumber");
                String licensePlateNumber = rs.getString("licensePlateNumber");
                String type = rs.getString("type");
                java.sql.Timestamp entryTime = rs.getTimestamp("time");
                Date date = rs.getDate("entryDate");
                
                tree.insert(ticketNumber, licensePlateNumber, type, entryTime, date);
            }

            query = "SELECT * FROM `exit`";
             pst = conn.prepareStatement(query);
             rs = pst.executeQuery();
             while (rs.next()) {
                int ticketNumber = rs.getInt("ticketNumber");
                String licensePlateNumber = rs.getString("liscensePlateNumber");
                String type = rs.getString("type");
                String entryTime = rs.getString("entryTime");
                String exitTime = rs.getString("exitTime");
                int duration = rs.getInt("duration");
                int tarif = rs.getInt("tarif");
                        
                treeExit.insert(ticketNumber, licensePlateNumber, type, entryTime, exitTime, duration, tarif);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void updateUsernameLabel() {
        if (formLogin != null) {
            String loggedInUsername = formLogin.getLoggedInUsername();
            usernameLogIn.setText(loggedInUsername);
        }
    }

    public dashboard(FormLogin formLogin) throws SQLException {
        this.formLogin = formLogin; 
        initComponents();
        updateUsernameLabel(); 
        tree = new Tree();
        treeExit = new TreeExit();
        getDataDatabase();
        
        
    }

    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLogIn = new javax.swing.JTextField();
        history = new javax.swing.JLabel();
        entry = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        baseDashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLogIn.setEditable(false);
        usernameLogIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLogInActionPerformed(evt);
            }
        });
        getContentPane().add(usernameLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 530, 138, 30));

        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });
        getContentPane().add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 120, 120));

        entry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entryMouseClicked(evt);
            }
        });
        getContentPane().add(entry, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 120, 120));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 120, 120));

        logOut.setBackground(new java.awt.Color(176, 57, 57));
        logOut.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        logOut.setText("LOG OUT");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 90, 30));

        baseDashboard.setBackground(new java.awt.Color(255, 255, 255));
        baseDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        getContentPane().add(baseDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed

        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure to  log out your account?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmation == JOptionPane.YES_OPTION) {
            this.dispose();
            FormLogin loginForm = new FormLogin();
            loginForm.setVisible(true);
        }

    }//GEN-LAST:event_logOutActionPerformed

    private void usernameLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLogInActionPerformed

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
        ParkingHistory history = new ParkingHistory(tree, treeExit);
        history.setVisible(true);
        dispose();
    }//GEN-LAST:event_historyMouseClicked

    private void entryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryMouseClicked
        EntryVehicle entry = new EntryVehicle(tree, treeExit);
        entry.setVisible(true);
        dispose();
    }//GEN-LAST:event_entryMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        if (tree == null) {
            ExitVehicle exit = new ExitVehicle();
            exit.setVisible(true);
            dispose();
        } else {
            ExitVehicle exit = new ExitVehicle(tree, treeExit);
            exit.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baseDashboard;
    private javax.swing.JLabel entry;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel history;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField usernameLogIn;
    // End of variables declaration//GEN-END:variables
}
